### ISSUE TITLE
Not compatible with IDEA2020.3

### ISSUE THREAD

**Issue by AprilViolet** [GoodforGod/DummyMapper#28]
**Describe the bug**
Not compatible with **IDEA2020.3**

**Comment by GoodforGod** [comment]
Hello, 
I'll try to release updated with new IDEA version support during weekends.
Thanks for issue!

**Comment by GoodforGod** [comment]
Can not be updated due to bug in IDEA 2020.3, will proceed after bug will be resolved

https://youtrack.jetbrains.com/issue/KT-42837

**Comment by tldzyx** [comment]
> Can not be updated due to bug in IDEA 2020.3, will proceed after bug will be resolved
> 
> https://youtrack.jetbrains.com/issue/KT-42837

Not compatible with IDEA2020.3.1, and [KT-42837](https://youtrack.jetbrains.com/issue/KTIJ-782) already fixed.

**Comment by GoodforGod** [comment]
New version new compatibility for 2020.3+ is publish and proceeding moderation by JetBrains, will be available probably on 12/13 January.
