### ISSUE TITLE
Optional objects

### ISSUE THREAD

**Issue by tomassatka** [GoodforGod/DummyMapper#38]
Does DummyMapper support nullable fields? In the README.md i dont see such example that would showcase an optional field that would be represented in schema as UNION with null hence the question. 

Example how to create nullable field/record/array would be highly appreciated.

**Comment by GoodforGod** [comment]
I suppose you are talking about Mapping as AVRO, actually yes it support nullable fields via **org.apache.avro.reflect.Nullable** annotation.

```
public class Person  {
    @Nullable
    private String name;
}
```
